### PR TITLE
Fix build for OS X

### PR DESCRIPTION
**Pull request by shellbj**

### CODE REVIEW

**Comment by Plethora777** [comment]
I do not have an OS X machine.  Are you able to compile and use mcpe_viz with these changes?

**Comment by shellbj** [comment]
Yes, I have a mostly working version running.  Things that aren't working seem to be already documented (png images too big).

**Comment by Plethora777** [comment]
Wow that's great to hear!  Could you write something up about how to compile on OS X?

**Comment by Plethora777** [comment]
That is -- anything that is needed that is different than what is in the README already

**Comment by shellbj** [comment]
There isn't anything special needed (as far as i can tell) beyond a compiler chain and development headers, if you want just the cmd line executable.  I can't really name everything you'd need starting out from a scratch system as I've already have a ton of things on here already.  I've built it with both gcc and xcode and likely using brew to pull in development headers (I didn't need any but I bet it used them).

I had to get xcode installed and then install qt to properly build the gui part; it seems to works, but I don't use it.

**Comment by Plethora777** [comment]
Very cool.  I'll pull this and update the README.  Thanks so much!

**Pull request merged**
